name: Discord Notification

on:
  workflow_dispatch:
  schedule:
    # Runs every day at 00:00 UTC.
    # Cancels if no new releases were published in the last 24 hours.
    - cron: '0 0 * * *'  

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Latest Release Data
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const { data: latestRelease } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            // Check if the latest release is a pre-release
            if (latestRelease.prerelease) {
              console.log('The latest release is a pre-release. Exiting.');
              core.setOutput('should_notify', 'false');
              return;
            }

            // Get the published date of the latest release
            const publishedAt = new Date(latestRelease.published_at);
            const now = new Date();
            const timeDifference = (now - publishedAt) / (1000 * 60 * 60);

            // Check if the release was published within the last 24 hours
            if (timeDifference > 24) {
              console.log('The latest release was published more than 24 hours ago. Exiting.');
              core.setOutput('should_notify', 'false');
              return;
            }

            // Set outputs if conditions are met
            core.setOutput('should_notify', 'true');
            core.setOutput('name', latestRelease.name || latestRelease.tag_name);
            core.setOutput('html_url', latestRelease.html_url);
            core.setOutput('body', latestRelease.body || '');
            core.setOutput('published_at', latestRelease.published_at);

      - name: Send Discord Notification
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          username: GitHub Releases
          color: '#ff00aa'
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          description: |
            # Launcher
            **New release published!**    
            Version: **${{ steps.get_release.outputs.name }}**
            [View release](${{ steps.get_release.outputs.html_url }})
          details: |
            ${{ steps.get_release.outputs.body }}
          # Default behaviour append a "- Today at 12:00 AM" to the footer
          # So just prefix with 'Released' to override the default footer
          footer: Released
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: No New Release Found
        if: steps.get_release.outputs.should_notify == 'false'
        run: echo "No new release to notify."
