name: Build and Release

on:
  push:
    branches:
      - master
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
      - develop

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install Wails CLI
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build binaries for Linux
        run: |
          mkdir -p build/linux
          wails build -platform linux/amd64 -o build/linux/Slender

      - name: Build binaries for Windows
        run: |
          mkdir -p build/windows
          wails build -platform windows/amd64 -o build/windows/Slender.exe

      - name: Semantic Release (Dry Run for PRs)
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GH_TOKEN: ${{ secrets.GHCR_TOKEN }}
        uses: semantic-release/semantic-release@v11.0.0
        with:
          args: |
            --ci
            --dry-run
            --repository-url=https://github.com/${{ github.repository }}
            --branches=master,develop

      - name: Semantic Release (Full Release on Push)
        if: ${{ github.event_name == 'push' }}
        env:
          GH_TOKEN: ${{ secrets.GHCR_TOKEN }}
        uses: semantic-release/semantic-release@v11.0.0
        with:
          args: |
            --ci
            --repository-url=https://github.com/${{ github.repository }}
            --branches=master,develop

      - name: Upload Linux Release Asset
        if: ${{ github.event_name == 'push' && success() }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          upload_url: ${{ steps['Semantic Release (Full Release on Push)'].outputs.upload_url }}
          asset_path: build/linux/Slender
          asset_name: Slender-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Windows Release Asset
        if: ${{ github.event_name == 'push' && success() }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          upload_url: ${{ steps['Semantic Release (Full Release on Push)'].outputs.upload_url }}
          asset_path: build/windows/Slender.exe
          asset_name: Slender-windows-amd64.exe
          asset_content_type: application/octet-stream
